import type { Overlook } from '../../game/types';

/* ============================================================
   OVERLOOKS — the idle stages. Each one is also a live widget.
   ============================================================ */

export const OVERLOOKS: Overlook[] = [
  {
    id: 'mistquay',
    name: '晨雾码头',
    nameEn: 'Mistlight Quay',
    region: '盐汐湾',
    blurb: '空船与咸风，最早醒来的是缆绳。',
    lore: '你在这里弹的第一支曲子，只有一只瞎眼的猫在听。它现在还来，坐在同一个缆桩上，像个付不出钱的老主顾。',
    scene: {
      kind: 'quay',
      palette: {
        dawn: ['#f7d9b6', '#f0b493', '#e39a86'],
        day: ['#b7d9e8', '#d8e9ee', '#f0e6d4'],
        dusk: ['#e9b183', '#c98d80', '#7c6a80'],
        night: ['#101c2e', '#1c2e44', '#2f4459'],
        ridge: ['#8fa8b4', '#6d8794', '#4c6472', '#2f4250'],
        ground: '#3b4a52',
        water: '#4b6d7d',
        accent: '#f5c67a',
        accent2: '#9fd7d1',
      },
      particles: ['gulls', 'mist'],
      water: 0.86,
      ridges: 3,
      jag: 0.35,
      stars: 0.8,
      horizon: 0.56,
    },
    base: { coin: 62, insp: 8, leisure: 3, renown: 0.35 },
    moods: ['sea', 'wind'],
    crowd: 0.35,
    townId: 'saltide',
    unlockNote: '起点。你唯一还回得去的地方。',
    mapPos: { x: 16, y: 84 },
  },
  {
    id: 'windmeadow',
    name: '风车麦原',
    nameEn: 'Windmill Meadow',
    region: '磨坊野',
    blurb: '麦子替你鼓掌，一整片地都在鼓掌。',
    lore: '磨坊主说，风车转得快的日子，音乐会传到三个村子外。他没说的是，那三个村子都不给钱。',
    scene: {
      kind: 'meadow',
      palette: {
        dawn: ['#ffe1b0', '#ffc98d', '#f5b57e'],
        day: ['#8ec5e6', '#c3e0e8', '#f2e3ba'],
        dusk: ['#f0b166', '#d98a5c', '#8b6a70'],
        night: ['#141f33', '#22314a', '#3d4b5c'],
        ridge: ['#a8bd8a', '#88a06c', '#657c4f', '#455838'],
        ground: '#c9a95f',
        accent: '#ffd98a',
        accent2: '#b6d17a',
      },
      particles: ['dust', 'leaves', 'fireflies'],
      water: 0,
      ridges: 4,
      jag: 0.22,
      stars: 0.9,
      horizon: 0.6,
    },
    base: { coin: 96, insp: 11, leisure: 3.2, renown: 0.5 },
    moods: ['wind', 'festive', 'forest'],
    crowd: 0.5,
    townId: 'millbrook',
    unlockNote: '主线第一章：把港口的债还清。',
    mapPos: { x: 33, y: 72 },
  },
  {
    id: 'petalbridge',
    name: '落樱石桥',
    nameEn: 'Petalfall Bridge',
    region: '樱水川',
    blurb: '花落得比钱快。',
    lore: '桥上永远有人在等另一个人。你替他们把等待唱成了曲子，于是等待变得可以忍受，你也就有了饭吃。',
    scene: {
      kind: 'bridge',
      palette: {
        dawn: ['#ffdfe6', '#ffc6cf', '#f3adb4'],
        day: ['#a8cfe8', '#d6e6ec', '#f7dde2'],
        dusk: ['#f2b3ba', '#cf8794', '#7d6478'],
        night: ['#161a30', '#252a48', '#3e3f5e'],
        ridge: ['#b9a4b6', '#9a8399', '#786379', '#54455a'],
        ground: '#6b5560',
        water: '#5d6f86',
        accent: '#ffc0cb',
        accent2: '#f7e7a8',
      },
      particles: ['petals', 'fireflies', 'mist'],
      water: 0.45,
      ridges: 4,
      jag: 0.3,
      stars: 0.85,
      horizon: 0.58,
    },
    base: { coin: 138, insp: 16, leisure: 3.4, renown: 0.75 },
    moods: ['floral', 'melancholy', 'city'],
    crowd: 0.65,
    townId: 'sakuraminato',
    unlockNote: '主线第二章：磨坊的失窃谷仓。',
    mapPos: { x: 52, y: 78 },
  },
  {
    id: 'cliffbeacon',
    name: '悬崖灯塔',
    nameEn: 'Cliffside Beacon',
    region: '潮鸣岬',
    blurb: '你和灯塔轮班，它照海，你照人。',
    lore: '守塔人耳背，却说你的曲子他听得最清。后来你才知道，他是靠脚下的石头在听。',
    scene: {
      kind: 'lighthouse',
      palette: {
        dawn: ['#f3c9a8', '#dfa693', '#b98a91'],
        day: ['#7fb6d8', '#adcfdd', '#dfd9c4'],
        dusk: ['#dd9a6f', '#a86f77', '#5d5470'],
        night: ['#0a1424', '#132339', '#22384d'],
        ridge: ['#5f7784', '#4a616f', '#354a58', '#213340'],
        ground: '#2b3b45',
        water: '#2f5468',
        accent: '#ffd27a',
        accent2: '#7fd0e8',
      },
      particles: ['gulls', 'mist', 'sparks'],
      water: 0.9,
      ridges: 3,
      jag: 0.5,
      stars: 1.15,
      horizon: 0.5,
    },
    base: { coin: 196, insp: 22, leisure: 3.6, renown: 1.1 },
    moods: ['sea', 'night', 'melancholy'],
    crowd: 0.4,
    townId: 'tidecall',
    unlockNote: '主线第三章：桥上那封没送到的信。',
    mapPos: { x: 26, y: 57 },
  },
  {
    id: 'emberkiln',
    name: '炉火窑台',
    nameEn: 'Emberkiln Terrace',
    region: '陶脊岭',
    blurb: '整座镇子是一炉不肯熄的火。',
    lore: '窑工们干活时不许唱歌，怕分心。所以他们付钱让你在窑外唱，一整夜。',
    scene: {
      kind: 'kiln',
      palette: {
        dawn: ['#ffd0a3', '#f0a179', '#cf7f6d'],
        day: ['#b9c4cf', '#d9d2c6', '#e8c9a5'],
        dusk: ['#ffb072', '#d0754f', '#6f4a4f'],
        night: ['#170f16', '#2a1a20', '#43262a'],
        ridge: ['#7d5f5c', '#634947', '#4a3436', '#331f24'],
        ground: '#3a2426',
        accent: '#ff9d4d',
        accent2: '#ffd88a',
      },
      particles: ['embers', 'sparks', 'dust'],
      water: 0,
      ridges: 4,
      jag: 0.4,
      stars: 0.7,
      horizon: 0.62,
    },
    base: { coin: 268, insp: 28, leisure: 3.8, renown: 1.4 },
    moods: ['city', 'festive', 'wind'],
    crowd: 0.8,
    townId: 'emberkiln',
    unlockNote: '主线第四章：灯塔守夜人的遗物。',
    mapPos: { x: 46, y: 60 },
  },
  {
    id: 'starfalldunes',
    name: '星穹沙丘',
    nameEn: 'Starfall Dunes',
    region: '沙月海',
    blurb: '没有观众的时候，就唱给会掉下来的东西听。',
    lore: '商队说这里的沙子会记住声音。你把一支只弹给自己听的曲子埋在了这里。',
    scene: {
      kind: 'dunes',
      palette: {
        dawn: ['#ffe0b5', '#f2b98a', '#d99a76'],
        day: ['#a8cbe0', '#dcd7bc', '#e8cb98'],
        dusk: ['#f0a86e', '#bb7a6e', '#6b5b78'],
        night: ['#08101f', '#131e34', '#27354a'],
        ridge: ['#c2a377', '#a8875d', '#8a6c47', '#65502f'],
        ground: '#c9a978',
        accent: '#ffe6a8',
        accent2: '#8fb4e8',
      },
      particles: ['dust', 'sparks'],
      water: 0,
      ridges: 5,
      jag: 0.12,
      stars: 1.5,
      horizon: 0.66,
      forceNight: false,
    },
    base: { coin: 356, insp: 40, leisure: 4, renown: 1.8 },
    moods: ['desert', 'night', 'sky'],
    crowd: 0.28,
    townId: 'moonsand',
    unlockNote: '主线第五章：窑火里烧出来的名字。',
    mapPos: { x: 72, y: 66 },
  },
  {
    id: 'cloudtea',
    name: '云上茶台',
    nameEn: 'Cloudtop Terrace',
    region: '浮岫峰',
    blurb: '云在你脚下走，观众在云里。',
    lore: '寺里的老僧只提一个要求：不要唱得太好，会让人不想下山。',
    scene: {
      kind: 'cloudtop',
      palette: {
        dawn: ['#ffe4c4', '#ffc9b0', '#f0b7bd'],
        day: ['#7db8e0', '#b8dbe8', '#f2f0e2'],
        dusk: ['#f7b585', '#d18b8f', '#6f6a8e'],
        night: ['#0d1526', '#1a2740', '#2e3f5c'],
        ridge: ['#9fb6c4', '#7d97a8', '#5c7688', '#3f5567'],
        ground: '#4a5f6d',
        accent: '#fff0c2',
        accent2: '#a8dce8',
      },
      particles: ['mist', 'lanternfly', 'gulls'],
      water: 0,
      ridges: 5,
      jag: 0.6,
      stars: 1.2,
      horizon: 0.68,
    },
    base: { coin: 470, insp: 56, leisure: 4.2, renown: 2.3 },
    moods: ['cloud', 'sky', 'holy'],
    crowd: 0.35,
    townId: 'cloudcloister',
    unlockNote: '主线第六章：沙里那支不属于你的曲子。',
    mapPos: { x: 60, y: 40 },
  },
  {
    id: 'auroralake',
    name: '极光冻湖',
    nameEn: 'Auroral Lake',
    region: '霜纹原',
    blurb: '冰面会把你的声音反弹回来，像有人合唱。',
    lore: '渔人说，冬天湖底有城。你弹了一夜，冰上裂出的纹路正好是五线谱。',
    scene: {
      kind: 'aurora',
      palette: {
        dawn: ['#dbe9f2', '#c2d8e8', '#a8c4d8'],
        day: ['#9ec6e0', '#c9dfeb', '#e8eff2'],
        dusk: ['#c4a8d8', '#8f8fc4', '#5c6b98'],
        night: ['#050d1c', '#0d1e33', '#183146'],
        ridge: ['#a8c2d4', '#83a2b8', '#5f7f96', '#3f5c73'],
        ground: '#cfe0e8',
        water: '#7fa8c2',
        accent: '#8fffd4',
        accent2: '#c4a8ff',
      },
      particles: ['snow', 'sparks'],
      water: 0.6,
      ridges: 4,
      jag: 0.45,
      stars: 1.6,
      horizon: 0.6,
      forceNight: true,
    },
    base: { coin: 620, insp: 78, leisure: 4.5, renown: 3,
    },
    moods: ['ice', 'night', 'holy'],
    crowd: 0.22,
    townId: 'frostweave',
    unlockNote: '主线第七章：山上那位不肯下山的听众。',
    mapPos: { x: 36, y: 27 },
  },
  /* ---------- special overlooks (side-line / secret) ---------- */
  {
    id: 'rainlane',
    name: '雨巷屋檐',
    nameEn: 'Rainlane Eaves',
    region: '旧灯街区',
    blurb: '屋檐是免费的舞台，代价是永远潮着。',
    lore: '一个卖伞的姑娘每天下雨都路过。你一直没想明白，她到底是来听曲子的，还是来卖伞的。',
    scene: {
      kind: 'rainlane',
      palette: {
        dawn: ['#cbd4dc', '#b4bfc9', '#9aa8b4'],
        day: ['#a8b8c4', '#c2ccd4', '#d8d4c9'],
        dusk: ['#8f8f9e', '#6f6f83', '#4f4f63'],
        night: ['#0f1420', '#1a2130', '#2a3242'],
        ridge: ['#6b7280', '#565d6b', '#414754', '#2d3340'],
        ground: '#333a45',
        water: '#3f4a58',
        accent: '#ffb85c',
        accent2: '#8fc4d8',
      },
      particles: ['rain', 'mist', 'lanternfly'],
      water: 0.18,
      ridges: 3,
      jag: 0.28,
      stars: 0.3,
      horizon: 0.54,
      forceRain: true,
    },
    base: { coin: 210, insp: 34, leisure: 4.4, renown: 1.2 },
    moods: ['rain', 'city', 'melancholy'],
    crowd: 0.55,
    special: true,
    townId: 'oldlamp',
    unlockNote: '支线《卖伞的人》。',
    mapPos: { x: 12, y: 68 },
  },
  {
    id: 'belltower',
    name: '废墟钟塔',
    nameEn: 'Ruined Belltower',
    region: '钟塔旧墟',
    blurb: '钟不响了，所以需要有人替它响。',
    lore: '这里曾有一整个乐团。他们留下的谱子被藤蔓翻过很多遍，比人翻得勤。',
    scene: {
      kind: 'belltower',
      palette: {
        dawn: ['#e8dcc4', '#cfbfa3', '#b0a189'],
        day: ['#b4c4b0', '#cfd4c2', '#ded8c2'],
        dusk: ['#c9a37f', '#95776f', '#5c5460'],
        night: ['#0b1218', '#161f26', '#25313a'],
        ridge: ['#8a9a86', '#6d7d69', '#51604e', '#38443a'],
        ground: '#3a453a',
        accent: '#c2ff9e',
        accent2: '#ffe3a8',
      },
      particles: ['fireflies', 'leaves', 'mist'],
      water: 0,
      ridges: 4,
      jag: 0.42,
      stars: 1.1,
      horizon: 0.6,
    },
    base: { coin: 330, insp: 66, leisure: 4.8, renown: 2.0 },
    moods: ['ruin', 'melancholy', 'forest'],
    crowd: 0.15,
    special: true,
    townId: 'bellruin',
    unlockNote: '支线《无人的乐团》。',
    mapPos: { x: 79, y: 46 },
  },
  {
    id: 'lanternwood',
    name: '灯笼林道',
    nameEn: 'Lanternwood',
    region: '祭夜林',
    blurb: '一年一次的夜，全林子都挂着人家的心愿。',
    lore: '有人把心愿写在灯笼上挂高，有人小声说出来。你两种都听见了。',
    scene: {
      kind: 'canopy',
      palette: {
        dawn: ['#ffd9b0', '#f0b58f', '#c98f7f'],
        day: ['#a8c2a0', '#c9d8b4', '#e0d8b8'],
        dusk: ['#ffab6b', '#c9765f', '#6b4f5c'],
        night: ['#0e1418', '#1c2620', '#2f3a2c'],
        ridge: ['#6b7d5c', '#556348', '#3f4a36', '#2b3325'],
        ground: '#2e3527',
        accent: '#ffb347',
        accent2: '#ffe08a',
      },
      particles: ['lanternfly', 'fireflies', 'embers', 'leaves'],
      water: 0,
      ridges: 4,
      jag: 0.3,
      stars: 0.9,
      horizon: 0.64,
      forceNight: true,
    },
    base: { coin: 540, insp: 60, leisure: 5.2, renown: 2.6 },
    moods: ['forest', 'festive', 'night'],
    crowd: 0.9,
    special: true,
    townId: 'lanternfair',
    unlockNote: '支线《挂得最高的那个》。',
    mapPos: { x: 66, y: 88 },
  },
  {
    id: 'whalefall',
    name: '鲸落天崖',
    nameEn: 'Whalefall Verge',
    region: '天海界',
    blurb: '天上有海，海里有鲸，鲸会停下来听。',
    lore: '这是所有云游者传说里最后一站。你原以为它不存在，直到有一只从云里探出头，对着你的琴声侧过身。',
    scene: {
      kind: 'whalefall',
      palette: {
        dawn: ['#ffdcc4', '#f7bcc4', '#d8a8c9'],
        day: ['#8fb8e0', '#b8d4e8', '#e8dce8'],
        dusk: ['#f2a8b4', '#b884b0', '#6b5f8f'],
        night: ['#060b1c', '#101a38', '#1f2e52'],
        ridge: ['#8f9ec4', '#6f7da8', '#525e8a', '#38416b'],
        ground: '#2e3557',
        accent: '#c4e8ff',
        accent2: '#ffc9e0',
      },
      particles: ['whales', 'sparks', 'mist'],
      water: 0,
      ridges: 5,
      jag: 0.55,
      stars: 1.8,
      horizon: 0.7,
      forceNight: true,
    },
    base: { coin: 880, insp: 120, leisure: 5.6, renown: 4.2 },
    moods: ['sky', 'sea', 'holy', 'night'],
    crowd: 0.1,
    special: true,
    townId: 'whalebone',
    unlockNote: '主线终章。',
    mapPos: { x: 52, y: 11 },
  },
];

export const OVERLOOK_MAP: Record<string, Overlook> = Object.fromEntries(
  OVERLOOKS.map((o) => [o.id, o]),
);
