import type { TownMap } from '../../game/types';

/* ============================================================
   TOWN MAPS — the exploration layer. Each overlook has a default
   town; special maps unlock from side stories.
   Node cost is paid in 闲暇 (Leisure), which only accrues while idling.
   ============================================================ */

export const TOWNS: TownMap[] = [
  {
    id: 'saltide',
    name: '盐汐港',
    nameEn: 'Saltide Harbour',
    blurb: '一个靠潮水记时间的港。每样东西上都有盐。',
    tint: '#cfe0e2',
    nodes: [
      {
        id: 'sal_market',
        name: '潮市摊列',
        kind: 'market',
        x: 26,
        y: 62,
        desc: '卖鱼、卖绳、也卖谱子。摊主认得所有欠钱的人。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_tide', 'it_string', 'it_rosin', 'it_wine', 'up_coffer'],
      },
      {
        id: 'sal_tavern',
        name: '断桨酒馆',
        kind: 'tavern',
        x: 47,
        y: 44,
        desc: '委托贴在门板上，用鱼骨钉着。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'sal_dock',
        name: '缆桩与旧船',
        kind: 'story',
        x: 68,
        y: 70,
        desc: '你最初摆摊的地方。有人在船底刻了一行字。',
        cost: 2,
        gain: { insp: 1, coin: 0.4 },
        loot: ['it_shell'],
      },
      {
        id: 'sal_dice',
        name: '舱底骰局',
        kind: 'gamble',
        x: 78,
        y: 40,
        desc: '三颗骰子，一盏油灯，一群不肯回家的人。',
        cost: 3,
        repeatable: true,
        minigame: 'dice',
      },
      {
        id: 'sal_luthier',
        name: '老陈的修琴铺',
        kind: 'luthier',
        x: 36,
        y: 28,
        desc: '他修琴不收钱，只收故事。乐器倒是要钱。',
        cost: 1,
        repeatable: true,
        shopStock: ['flute_silver', 'guitar_road', 'violin_ash', 'it_string'],
      },
      {
        id: 'sal_warehouse',
        name: '旧仓库夹层',
        kind: 'story',
        x: 88,
        y: 62,
        desc: '门上有个猫大小的洞。',
        cost: 4,
        gain: { insp: 1.5 },
        loot: ['it_button'],
      },
      {
        id: 'sal_shrine',
        name: '咸风小祠',
        kind: 'shrine',
        x: 14,
        y: 36,
        desc: '出海的人在这里留一枚铜板，回来的人取走两枚。',
        cost: 2,
        repeatable: true,
        cooldown: 90,
        gain: { renown: 2, insp: 0.6 },
      },
    ],
  },
  {
    id: 'millbrook',
    name: '磨坊村',
    nameEn: 'Millbrook',
    blurb: '四座风车，三家酒馆，一个总在丢东西的谷仓。',
    tint: '#e6dcb4',
    nodes: [
      {
        id: 'mil_barn',
        name: '失窃的谷仓',
        kind: 'story',
        x: 30,
        y: 66,
        desc: '锁没被撬开，麦子却少了三袋。',
        cost: 3,
        gain: { insp: 1.2, coin: 0.6 },
        loot: ['it_wheat'],
      },
      {
        id: 'mil_market',
        name: '谷物集',
        kind: 'market',
        x: 52,
        y: 52,
        desc: '每周一次，卖的东西比你见过的都实在。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_wheat', 'accordion', 'it_rosin', 'it_wine', 'up_apprentice', 'up_umbrella'],
      },
      {
        id: 'mil_tavern',
        name: '三风酒馆',
        kind: 'tavern',
        x: 68,
        y: 34,
        desc: '风向不对的日子这里的人特别多。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'mil_puzzle',
        name: '风车的节拍',
        kind: 'puzzle',
        x: 20,
        y: 32,
        desc: '四座风车转速不同。磨坊主说，谁能跟上，谁就懂了这块地。',
        cost: 3,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'mil_cards',
        name: '收割节纸牌',
        kind: 'gamble',
        x: 82,
        y: 62,
        desc: '牌是手绘的，一半的花色都掉了色。',
        cost: 3,
        repeatable: true,
        minigame: 'cards',
      },
      {
        id: 'mil_scribe',
        name: '旧谱箱',
        kind: 'scribe',
        x: 44,
        y: 22,
        desc: '磨坊主祖父留下的一箱谱子，没人识谱。',
        cost: 2,
        repeatable: true,
        /* song_ferry is the one everybody already knows — it is the
           starting song and carries no price, so it stays off the shelf */
        shopStock: ['song_tide', 'song_wheat'],
      },
      {
        id: 'mil_shrine',
        name: '麦田稻草人',
        kind: 'shrine',
        x: 62,
        y: 76,
        desc: '给它戴上帽子的人，那一年都不缺饭。',
        cost: 2,
        repeatable: true,
        cooldown: 90,
        gain: { renown: 3, coin: 0.5 },
      },
    ],
  },
  {
    id: 'sakuraminato',
    name: '樱水町',
    nameEn: 'Sakuraminato',
    blurb: '一条河，一座桥，和无数个在桥上等人的故事。',
    tint: '#f2dfe2',
    nodes: [
      {
        id: 'sak_post',
        name: '驿站与信匣',
        kind: 'story',
        x: 34,
        y: 40,
        desc: '有一格信匣积了三年的灰，收信人的名字被水泡了。',
        cost: 4,
        gain: { insp: 1.8 },
        loot: ['it_petal'],
      },
      {
        id: 'sak_market',
        name: '花街铺',
        kind: 'market',
        x: 56,
        y: 60,
        desc: '什么都卖，什么都贵一成。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_letter', 'kalimba', 'xiao_mist', 'guzheng_river', 'up_lantern', 'up_journal', 'it_wine'],
      },
      {
        id: 'sak_tavern',
        name: '桥下茶寮',
        kind: 'tavern',
        x: 72,
        y: 44,
        desc: '茶比酒贵，委托比茶多。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'sak_puzzle',
        name: '石桥的十七级',
        kind: 'puzzle',
        x: 20,
        y: 62,
        desc: '每级台阶敲起来音高不同。有人按顺序敲过，桥下就有回声。',
        cost: 3,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'sak_dice',
        name: '河灯赌局',
        kind: 'gamble',
        x: 82,
        y: 70,
        desc: '押哪盏河灯先熄。听起来很雅，其实很凶。',
        cost: 3,
        repeatable: true,
        minigame: 'dice',
      },
      {
        id: 'sak_scribe',
        name: '抄谱人小铺',
        kind: 'scribe',
        x: 44,
        y: 22,
        desc: '一个只用左手写字的人，抄一页收一枚。',
        cost: 2,
        repeatable: true,
        shopStock: ['song_letter', 'song_beacon', 'song_rain'],
      },
      {
        id: 'sak_shrine',
        name: '结缘石',
        kind: 'shrine',
        x: 66,
        y: 24,
        desc: '两块石头之间系满了绳子。有些绳子已经断了。',
        cost: 2,
        repeatable: true,
        cooldown: 90,
        gain: { renown: 4, insp: 0.8 },
      },
    ],
  },
  {
    id: 'tidecall',
    name: '潮鸣崖村',
    nameEn: 'Tidecall',
    blurb: '十九户人家，一座灯塔，全村都听得见浪。',
    tint: '#cdd9de',
    nodes: [
      {
        id: 'tid_tower',
        name: '守夜人的塔',
        kind: 'story',
        x: 74,
        y: 30,
        desc: '塔顶的记录本停在某一天，那一页只写了半句。',
        cost: 5,
        gain: { insp: 2.2, renown: 3 },
        loot: ['it_lens'],
      },
      {
        id: 'tid_market',
        name: '崖顶杂货',
        kind: 'market',
        x: 40,
        y: 56,
        desc: '进货靠一条绳子和一个滑轮。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_beacon', 'horn_post', 'up_pass', 'up_dice', 'it_string', 'it_wine'],
      },
      {
        id: 'tid_tavern',
        name: '灯下酒馆',
        kind: 'tavern',
        x: 24,
        y: 40,
        desc: '灯塔的光每十二秒扫过一次窗。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'tid_puzzle',
        name: '灯语',
        kind: 'puzzle',
        x: 58,
        y: 68,
        desc: '守夜人用长短光和外海说话。你能学会。',
        cost: 4,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'tid_luthier',
        name: '渔线换弦匠',
        kind: 'luthier',
        x: 16,
        y: 66,
        desc: '他能用渔线做出比银弦更亮的音。',
        cost: 2,
        repeatable: true,
        shopStock: ['harp_tide', 'cello_tide', 'it_string'],
      },
      {
        id: 'tid_shrine',
        name: '海难碑',
        kind: 'shrine',
        x: 88,
        y: 58,
        desc: '碑上一百四十个名字，有九个是同一个姓。',
        cost: 3,
        repeatable: true,
        cooldown: 120,
        gain: { renown: 5, insp: 1 },
      },
    ],
  },
  {
    id: 'emberkiln',
    name: '炉火窑镇',
    nameEn: 'Emberkiln',
    blurb: '一年三百天在烧窑，剩下的六十五天在庆祝烧完了。',
    tint: '#e8cdb4',
    nodes: [
      {
        id: 'emb_kiln',
        name: '开窑的那一炉',
        kind: 'story',
        x: 48,
        y: 36,
        desc: '这一炉里有一批不是陶器的东西。',
        cost: 5,
        gain: { insp: 2, coin: 1.2 },
        loot: ['it_glaze', 'it_score_burnt'],
      },
      {
        id: 'emb_market',
        name: '陶器集市',
        kind: 'market',
        x: 26,
        y: 56,
        desc: '摔了的算你的，没摔的也算你的。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_ember', 'drum_kiln', 'suona_kiln', 'up_cushion', 'up_whistle', 'it_wine'],
      },
      {
        id: 'emb_tavern',
        name: '釉色酒馆',
        kind: 'tavern',
        x: 66,
        y: 60,
        desc: '酒杯全是窑变废品，每个都不一样。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'emb_gamble',
        name: '窑工的赌桌',
        kind: 'gamble',
        x: 80,
        y: 32,
        desc: '赌的是下一炉出几件好货。',
        cost: 4,
        repeatable: true,
        minigame: 'dice',
      },
      {
        id: 'emb_puzzle',
        name: '火候',
        kind: 'puzzle',
        x: 18,
        y: 30,
        desc: '老师傅听火的声音判断温度。这也是一种听力。',
        cost: 4,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'emb_shrine',
        name: '窑神龛',
        kind: 'shrine',
        x: 60,
        y: 78,
        desc: '龛前的灰堆里全是烧过的谢词。',
        cost: 3,
        repeatable: true,
        cooldown: 120,
        gain: { renown: 6, coin: 0.8 },
      },
    ],
  },
  {
    id: 'moonsand',
    name: '沙月商队营',
    nameEn: 'Moonsand Camp',
    blurb: '一座会移动的城，帐篷比人多。',
    tint: '#eddcb8',
    nodes: [
      {
        id: 'moo_dig',
        name: '沙下的东西',
        kind: 'story',
        x: 70,
        y: 62,
        desc: '风把沙吹开了半尺，露出一段木头，木头上有弦孔。',
        cost: 6,
        gain: { insp: 3 },
        loot: ['it_sandglass'],
      },
      {
        id: 'moo_market',
        name: '商队货栈',
        kind: 'market',
        x: 40,
        y: 46,
        desc: '这里能买到别处买不到的，也能买到别处不该有的。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_dune', 'lyre_star', 'up_ring', 'up_pass', 'it_wine'],
      },
      {
        id: 'moo_tavern',
        name: '篷布下的酒',
        kind: 'tavern',
        x: 24,
        y: 62,
        desc: '所有人都在等风停。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'moo_cards',
        name: '沙月牌局',
        kind: 'gamble',
        x: 84,
        y: 40,
        desc: '牌背是月相。老手看背面就知道你手上有什么。',
        cost: 4,
        repeatable: true,
        minigame: 'cards',
      },
      {
        id: 'moo_puzzle',
        name: '星图',
        kind: 'puzzle',
        x: 54,
        y: 22,
        desc: '商队认路不看地，看天。',
        cost: 5,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'moo_shrine',
        name: '沙中石堆',
        kind: 'shrine',
        x: 16,
        y: 34,
        desc: '每个路过的人加一块石头。石堆已经比人高了。',
        cost: 3,
        repeatable: true,
        cooldown: 120,
        gain: { renown: 7, insp: 1.2 },
      },
    ],
  },
  {
    id: 'cloudcloister',
    name: '云顶寺',
    nameEn: 'Cloudtop Cloister',
    blurb: '一座寺，十二级石阶，和一整片在下面的云。',
    tint: '#d9e2e6',
    nodes: [
      {
        id: 'clo_hall',
        name: '老僧的堂',
        kind: 'story',
        x: 50,
        y: 30,
        desc: '堂里只有一个蒲团、一只茶壶和一个不肯下山的人。',
        cost: 6,
        gain: { insp: 3.2, renown: 5 },
        loot: ['it_teabrick'],
      },
      {
        id: 'clo_market',
        name: '寺前茶摊',
        kind: 'market',
        x: 30,
        y: 58,
        desc: '茶三种，价钱一样，看你想不想下山。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_cloud', 'harmonium_pilgrim', 'up_cart', 'up_ring', 'it_wine'],
      },
      {
        id: 'clo_puzzle',
        name: '十二级石阶',
        kind: 'puzzle',
        x: 72,
        y: 62,
        desc: '踩上去，每级的回声都不同。据说踩对顺序云会散开。',
        cost: 5,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'clo_scribe',
        name: '藏经的谱',
        kind: 'scribe',
        x: 20,
        y: 34,
        desc: '经卷背面有人偷偷抄了曲子。',
        cost: 4,
        repeatable: true,
        shopStock: ['song_cloud', 'song_ice'],
      },
      {
        id: 'clo_shrine',
        name: '云上钟',
        kind: 'shrine',
        x: 82,
        y: 32,
        desc: '敲一次，云会短暂地让出一条路。',
        cost: 4,
        repeatable: true,
        cooldown: 150,
        gain: { renown: 9, insp: 1.6 },
      },
    ],
  },
  {
    id: 'frostweave',
    name: '冰纹渔屯',
    nameEn: 'Frostweave',
    blurb: '冬天凿冰捕鱼，夏天修补冬天弄坏的东西。',
    tint: '#dbe8ee',
    nodes: [
      {
        id: 'fro_hole',
        name: '冰洞',
        kind: 'story',
        x: 62,
        y: 64,
        desc: '渔人凿的洞。往下看，能看见不该在湖底的东西。',
        cost: 7,
        gain: { insp: 3.6, renown: 6 },
        loot: ['it_icecore'],
      },
      {
        id: 'fro_market',
        name: '冻货铺',
        kind: 'market',
        x: 34,
        y: 48,
        desc: '什么都冻着，包括账本。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_ice', 'up_pass2', 'up_cart', 'it_wine'],
      },
      {
        id: 'fro_tavern',
        name: '火塘',
        kind: 'tavern',
        x: 20,
        y: 66,
        desc: '全屯唯一不结冰的地方。',
        cost: 0,
        repeatable: true,
      },
      {
        id: 'fro_puzzle',
        name: '冰裂纹',
        kind: 'puzzle',
        x: 78,
        y: 36,
        desc: '裂纹的走向像谱子。按它弹，湖会答。',
        cost: 6,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'fro_shrine',
        name: '湖神石',
        kind: 'shrine',
        x: 46,
        y: 26,
        desc: '每年第一条鱼要放在这里。今年的还在。',
        cost: 4,
        repeatable: true,
        cooldown: 150,
        gain: { renown: 11, insp: 1.8 },
      },
    ],
  },
  /* ---------------- special maps ---------------- */
  {
    id: 'oldlamp',
    name: '旧灯街区',
    nameEn: 'Old Lamp Quarter',
    blurb: '城里唯一还在用油灯的一片。所以永远看着像在下雨。',
    tint: '#d4d8dc',
    special: true,
    nodes: [
      {
        id: 'old_umbrella',
        name: '伞铺',
        kind: 'story',
        x: 40,
        y: 40,
        desc: '门口挂着一排素面伞，最里面那把没有价钱。',
        cost: 4,
        gain: { insp: 2.4 },
        loot: ['it_umbrella_paper'],
      },
      {
        id: 'old_market',
        name: '雨中夜市',
        kind: 'market',
        x: 64,
        y: 58,
        desc: '雨天生意最好，因为没人想回家。',
        cost: 0,
        repeatable: true,
        shopStock: ['song_rain', 'kalimba', 'erhu_dusk', 'up_umbrella', 'up_journal', 'it_wine'],
      },
      {
        id: 'old_dice',
        name: '巷口骰摊',
        kind: 'gamble',
        x: 22,
        y: 66,
        desc: '摊子有个雨棚，赌客没有。',
        cost: 3,
        repeatable: true,
        minigame: 'dice',
      },
      {
        id: 'old_puzzle',
        name: '屋檐滴水',
        kind: 'puzzle',
        x: 76,
        y: 30,
        desc: '七个屋檐，七种滴水的间隔。合起来是一支曲子。',
        cost: 4,
        repeatable: true,
        minigame: 'tune',
      },
    ],
  },
  {
    id: 'bellruin',
    name: '钟塔旧墟',
    nameEn: 'Bellruin',
    blurb: '一座塔，十七个乐谱架，没有一个人。',
    tint: '#dae0cf',
    special: true,
    nodes: [
      {
        id: 'bel_bell',
        name: '钟舌',
        kind: 'story',
        x: 52,
        y: 30,
        desc: '钟还在，舌头掉在地上，藤蔓已经缠上去了。',
        cost: 5,
        gain: { insp: 2.8, renown: 4 },
        loot: ['it_bellclapper'],
      },
      {
        id: 'bel_score',
        name: '散落的声部',
        kind: 'story',
        x: 28,
        y: 60,
        desc: '十七个谱架，十七个声部。少了指挥的那一份。',
        cost: 6,
        gain: { insp: 3.4 },
      },
      {
        id: 'bel_puzzle',
        name: '十七个声部',
        kind: 'puzzle',
        x: 74,
        y: 58,
        desc: '要把它们合起来，你得先记住每一个的进入点。',
        cost: 6,
        repeatable: true,
        minigame: 'tune',
      },
      {
        id: 'bel_shrine',
        name: '乐团的碑',
        kind: 'shrine',
        x: 66,
        y: 76,
        desc: '碑上没有名字，只有十七道刻痕。',
        cost: 4,
        repeatable: true,
        cooldown: 150,
        gain: { renown: 10, insp: 2 },
      },
    ],
  },
  {
    id: 'lanternfair',
    name: '灯笼林集',
    nameEn: 'Lantern Fair',
    blurb: '一年只开一夜的集市，卖的东西第二天全部不存在。',
    tint: '#eddac0',
    special: true,
    nodes: [
      {
        id: 'lan_tree',
        name: '最高的一枝',
        kind: 'story',
        x: 54,
        y: 26,
        desc: '要爬上去，得先放下琴。',
        cost: 6,
        gain: { insp: 3, renown: 8 },
        loot: ['it_lanternslip'],
      },
      {
        id: 'lan_market',
        name: '灯笼摊',
        kind: 'market',
        x: 30,
        y: 56,
        desc: '摊主说，卖的不是灯笼，是一夜。',
        cost: 0,
        repeatable: true,
        shopStock: ['up_whistle', 'up_cart', 'lyre_star', 'yangqin_moon', 'it_wine'],
      },
      {
        id: 'lan_cards',
        name: '祭夜牌局',
        kind: 'gamble',
        x: 74,
        y: 62,
        desc: '赢的人许愿，输的人替他挂灯笼。',
        cost: 5,
        repeatable: true,
        minigame: 'cards',
      },
    ],
  },
  {
    id: 'whalebone',
    name: '鲸骨集',
    nameEn: 'Whalebone Market',
    blurb: '天海界唯一的落脚点。整个集市搭在一根肋骨上。',
    tint: '#d8dceb',
    special: true,
    nodes: [
      {
        id: 'wha_map',
        name: '云游者旧图',
        kind: 'story',
        x: 48,
        y: 34,
        desc: '摊子最深处压着一张图，标了十二个点。',
        cost: 8,
        gain: { insp: 4, renown: 10 },
        loot: ['it_map_old'],
      },
      {
        id: 'wha_market',
        name: '鲸骨市',
        kind: 'market',
        x: 26,
        y: 58,
        desc: '这里的东西不标价，摊主看你的琴。',
        cost: 0,
        repeatable: true,
        shopStock: ['up_pass2', 'up_ring', 'trombone_harbor', 'it_wine'],
      },
      {
        id: 'wha_shrine',
        name: '天海祠',
        kind: 'shrine',
        x: 74,
        y: 52,
        desc: '祠里没有神像，只有一个朝上的空位。',
        cost: 5,
        repeatable: true,
        cooldown: 180,
        gain: { renown: 16, insp: 3 },
      },
    ],
  },
];

export const TOWN_MAP: Record<string, TownMap> = Object.fromEntries(TOWNS.map((t) => [t.id, t]));

export const NODE_MAP: Record<string, { node: TownMap['nodes'][number]; townId: string }> =
  Object.fromEntries(
    TOWNS.flatMap((t) => t.nodes.map((n) => [n.id, { node: n, townId: t.id }])),
  );
