import type { GameEvent } from '../../game/types';

/* ============================================================
   EVENTS — what happens while you are not looking.

   CONVENTION for `gain` / `cost`:
     coin    → measured in HOURS OF CURRENT TIP INCOME (0.5 = half an hour of tips)
     insp    → measured in HOURS OF CURRENT INSPIRATION
     renown  → flat renown points
     leisure → flat leisure points
   This keeps every event meaningful at every stage of the game.
   ============================================================ */

export const EVENTS: GameEvent[] = [
  /* ---------------- ambient / passive ---------------- */
  {
    id: 'ev_cat',
    title: '瞎眼猫来了',
    text: '那只瞎眼的猫又坐上了缆桩，一动不动听完了整首。走的时候在你琴箱边留了半条鱼。',
    weight: 10,
    moods: ['sea'],
    tone: 'warm',
    gain: { insp: 0.4 },
  },
  {
    id: 'ev_drunk',
    title: '醉汉点单',
    text: '一个醉汉要你连弹七遍同一首。第七遍他睡着了，钱包朝上。你只拿了他答应的那份。',
    weight: 9,
    moods: [],
    tone: 'odd',
    gain: { coin: 0.7 },
  },
  {
    id: 'ev_child',
    title: '不肯走的小孩',
    text: '一个小孩听了两小时，最后把攥出汗的一枚铜板放进琴箱，跑掉了。你一直没花那枚。',
    weight: 8,
    moods: [],
    tone: 'warm',
    gain: { coin: 0.2, insp: 0.6, renown: 2 },
  },
  {
    id: 'ev_merchant',
    title: '路过的商队',
    text: '商队停下歇脚，管事的听得高兴，让人抬了半袋铜过来，说抵一晚的觉。',
    weight: 8,
    moods: ['desert', 'wind', 'city'],
    tone: 'lucky',
    gain: { coin: 1.6 },
  },
  {
    id: 'ev_rainstop',
    title: '雨停的那一刻',
    text: '雨忽然停了，所有屋檐同时开始滴水。你顺着这个节奏改了一段，比原曲好。',
    weight: 9,
    moods: ['rain', 'city', 'melancholy'],
    tone: 'warm',
    gain: { insp: 1.2 },
  },
  {
    id: 'ev_gull',
    title: '海鸥抢戏',
    text: '一只海鸥叼走了你放在琴箱上的面包，又飞回来落在你肩上，像是道歉。',
    weight: 7,
    moods: ['sea'],
    tone: 'odd',
    item: 'it_feather',
  },
  {
    id: 'ev_star',
    title: '掉下来的东西',
    text: '你抬头的时候正好看见一颗划过去。沙丘上有人喊了一声，然后所有人都安静了很久。',
    weight: 8,
    moods: ['desert', 'sky', 'night'],
    tone: 'grand',
    gain: { insp: 1.8, renown: 3 },
  },
  {
    id: 'ev_bell',
    title: '钟自己响了',
    text: '半夜里那口坏钟响了一声。你查过，绳子还是断的。',
    weight: 7,
    moods: ['ruin'],
    tone: 'eerie',
    gain: { insp: 1.5 },
  },
  {
    id: 'ev_aurora',
    title: '极光低下来了',
    text: '光带压得很低，几乎贴上了冰面。你停下手，只是看。什么也没赚到。',
    weight: 8,
    moods: ['ice', 'night'],
    tone: 'grand',
    gain: { insp: 2.2, renown: 4 },
  },
  {
    id: 'ev_whale',
    title: '它侧了一下身',
    text: '云里那只慢慢转过来，把一侧的鳍朝向你。你弹的每一个音它都跟着轻轻沉一下。',
    weight: 9,
    moods: ['sky'],
    tone: 'grand',
    gain: { insp: 3, renown: 8, coin: 1.5 },
  },
  {
    id: 'ev_couple',
    title: '桥上的两个人',
    text: '一对在桥上吵架的人，听到一半就不吵了。走的时候男的回头给你留了一整袋。',
    weight: 8,
    moods: ['floral', 'city', 'melancholy'],
    tone: 'warm',
    gain: { coin: 1.3, renown: 2 },
  },
  {
    id: 'ev_kiln',
    title: '窑开了',
    text: '开窑那一刻整条街都在看。有人把烧坏的一片塞给你："这个颜色配你的曲子。"',
    weight: 8,
    moods: ['city', 'festive'],
    tone: 'warm',
    item: 'it_glaze',
  },
  {
    id: 'ev_monk',
    title: '老僧续茶',
    text: '你弹完，老僧一句话也没说，只是把你的杯子续满了。你觉得这比掌声难得。',
    weight: 7,
    moods: ['cloud', 'holy'],
    tone: 'warm',
    gain: { insp: 1.6, renown: 3 },
  },
  {
    id: 'ev_lanterns',
    title: '灯笼放起来了',
    text: '整条林道的灯笼同时升起来。你的曲子被数百个人的心愿盖过去了，你不介意。',
    weight: 9,
    moods: ['festive', 'forest'],
    tone: 'grand',
    gain: { coin: 2.2, renown: 5 },
  },
  {
    id: 'ev_string',
    title: '断了一根弦',
    text: '第三弦崩了，弹到了手背。你用剩下的弦把那首曲子改完了，围观的人反而更多。',
    weight: 8,
    moods: [],
    tone: 'odd',
    gain: { coin: -0.3, insp: 1.1, renown: 2 },
  },
  {
    id: 'ev_thief',
    title: '有人摸琴箱',
    text: '一个瘦得厉害的孩子伸手进了琴箱。你继续弹，只是把脚往箱子那边挪了一寸。他拿走了几个铜板。',
    weight: 7,
    moods: ['city'],
    tone: 'sad',
    gain: { coin: -0.5, renown: 1 },
  },
  {
    id: 'ev_wind',
    title: '风把谱子吹走了',
    text: '整叠谱纸飞出去。等你捡回来的时候，少了一页——你至今不知道那一页写的是什么。',
    weight: 7,
    moods: ['wind', 'cloud'],
    tone: 'sad',
    gain: { insp: -0.4, coin: 0.2 },
  },
  {
    id: 'ev_wedding',
    title: '临时被请去婚礼',
    text: '一场没请到乐师的婚礼把你抓了去。他们付得比一整天摆摊多。',
    weight: 6,
    moods: ['festive', 'city', 'floral'],
    tone: 'lucky',
    gain: { coin: 3.2, renown: 4 },
  },
  {
    id: 'ev_funeral',
    title: '有人要你弹送葬',
    text: '他们不知道该请谁，就请了你。你弹了一支从没弹过的曲子。没人给钱，也没人走。',
    weight: 6,
    moods: ['melancholy', 'ruin', 'night'],
    tone: 'sad',
    gain: { insp: 2.4, renown: 5 },
  },
  {
    id: 'ev_coinstack',
    title: '有人放了一整叠',
    text: '一个穿得极普通的人站着听完，把一叠整钱压在琴箱底，然后走了，没留名字。',
    weight: 4,
    moods: [],
    minRenown: 40,
    tone: 'lucky',
    gain: { coin: 4.5 },
  },
  {
    id: 'ev_rival',
    title: '来了个抢地盘的',
    text: '另一个吟游诗人在你对面五步开外摆了摊。你们对弹了两个小时，最后合奏了半小时，分了钱。',
    weight: 6,
    moods: ['city', 'festive'],
    tone: 'odd',
    gain: { coin: 0.8, insp: 1.4, renown: 3 },
  },
  {
    id: 'ev_snow',
    title: '雪把声音吃掉了',
    text: '雪大得听不见自己的琴。你弹了整夜，第二天雪地上只有一个人的脚印是新的。',
    weight: 7,
    moods: ['ice'],
    tone: 'eerie',
    gain: { insp: 1.8, coin: -0.2 },
  },
  {
    id: 'ev_shellgift',
    title: '有人用贝壳付账',
    text: '"我没有钱，但这个比钱好看。" 你收了。她说得对。',
    weight: 8,
    moods: ['sea'],
    tone: 'warm',
    item: 'it_shell',
  },

  /* ---------------- decision events ---------------- */
  {
    id: 'ev_choice_captain',
    title: '船长的邀请',
    text: '一个船长听完全程，说他要出海三个月，缺一个能让水手不打架的人。他在等你的答复。',
    weight: 7,
    moods: ['sea'],
    tone: 'odd',
    choices: [
      {
        label: '上船三个月',
        detail: '一大笔预付，但你会错过这里的一切',
        gain: { coin: 6 },
        cost: { insp: 1.5 },
        outcome: '你拿了预付，最后没上船。船长回来时什么也没说，只是再也没在你面前停下过。',
      },
      {
        label: '婉拒，留在岸上',
        detail: '换一枚黄铜纽扣和一句祝福',
        item: 'it_button',
        gain: { renown: 3 },
        outcome: '他把军装上的一枚纽扣拆下来给你："岸上的人也需要有人弹琴。"',
      },
    ],
  },
  {
    id: 'ev_choice_bet',
    title: '窑工的赌局',
    text: '几个窑工要跟你赌一把：他们出题，你现场把题目编成曲子，编得出，桌上的钱都是你的。',
    weight: 8,
    moods: ['city', 'festive'],
    tone: 'lucky',
    choices: [
      {
        label: '赌',
        detail: '赢面看灵感，赢了三倍，输了赔一半',
        gain: { coin: 3 },
        cost: { insp: 1 },
        outcome: '题目是"一只掉进釉桶的老鼠"。你编完，他们笑得直不起腰，钱全推给了你。',
      },
      {
        label: '不赌，请他们喝一轮',
        detail: '花点钱，换一群铁杆听众',
        cost: { coin: 0.8 },
        gain: { renown: 6 },
        outcome: '从那天起，只要你在窑台上出现，第一排永远是他们。',
      },
    ],
  },
  {
    id: 'ev_choice_umbrella',
    title: '卖伞的姑娘',
    text: '雨里有个卖伞的姑娘站了很久，一把也没卖出去。她问你：要不要一把？',
    weight: 9,
    moods: ['rain', 'city'],
    tone: 'warm',
    flag: 'flag_umbrella_met',
    choices: [
      {
        label: '买一把',
        detail: '你其实不缺伞',
        cost: { coin: 0.6 },
        item: 'it_umbrella_paper',
        gain: { insp: 1.2 },
        outcome: '她挑了最素的一把给你，收了最便宜的价。"下次别站在漏水的那一格。"',
      },
      {
        label: '给她弹一首',
        detail: '不要钱',
        gain: { insp: 2, renown: 4 },
        item: 'it_umbrella_paper',
        outcome: '你弹完，她把那把素面伞放在你脚边就走了，一句话没说。伞是干的。',
      },
    ],
  },
  {
    id: 'ev_choice_score',
    title: '一页别人的谱子',
    text: '风吹来一页手写谱，字迹很老。右下角有个签名，被水泡花了。有人在远处四处张望，像在找什么。',
    weight: 7,
    moods: ['ruin', 'wind', 'melancholy'],
    tone: 'eerie',
    choices: [
      {
        label: '收进自己的谱袋',
        detail: '这一页确实好',
        gain: { insp: 2.5 },
        item: 'it_score_burnt',
        outcome: '你把它抄进了自己的册子。那段旋律后来救过你两次场，你一次也没说它不是你的。',
      },
      {
        label: '还给那个人',
        detail: '你猜他找的就是这个',
        gain: { renown: 8, coin: 1 },
        outcome: '那是个瞎了一只眼的老乐师。他摸着纸哭了，然后把身上的钱全给了你，说"这页我找了十九年"。',
      },
    ],
  },
  {
    id: 'ev_choice_noble',
    title: '贵人的马车',
    text: '一辆马车停下来，车里的人不下来，只递出一张纸条：明晚，私人宴，价钱随你开。',
    weight: 5,
    moods: [],
    minRenown: 60,
    tone: 'odd',
    choices: [
      {
        label: '去，开个高价',
        detail: '钱很多，代价是这一带的人会觉得你走了',
        gain: { coin: 8 },
        cost: { renown: 5 },
        outcome: '宴上无人真听。你收了很多钱，回来时街角的老位置被人占了。',
      },
      {
        label: '不去，第二天照常摆摊',
        detail: '街上的人会记住这件事',
        gain: { renown: 12, insp: 1 },
        outcome: '不知怎么，全街都知道了你拒绝了马车。那天琴箱满得盖不上。',
      },
    ],
  },
  {
    id: 'ev_choice_apprentice',
    title: '想跟你学的人',
    text: '一个十四五岁的孩子跪在你摊子前，说他什么都能干，只要你教他。',
    weight: 6,
    moods: [],
    minRenown: 30,
    tone: 'warm',
    choices: [
      {
        label: '收下他',
        detail: '多一张嘴，也多一双手',
        cost: { coin: 1.2 },
        gain: { renown: 6 },
        flag: 'flag_apprentice',
        outcome: '他学得慢，但从不迟到。你出摊时他替你占位置，你收摊时他替你数钱。',
      },
      {
        label: '让他先回家',
        detail: '这条路你自己都还没走明白',
        gain: { insp: 1.4 },
        outcome: '他走的时候没哭。三年后你在另一个镇子上听到有人弹你的曲子，弹得比你规矩。',
      },
    ],
  },
  {
    id: 'ev_choice_ice',
    title: '冰面下的敲击',
    text: '半夜，你脚下的冰被敲了三下。间隔很准，是三拍子。',
    weight: 6,
    moods: ['ice', 'night'],
    tone: 'eerie',
    choices: [
      {
        label: '照着敲回去',
        detail: '看它答不答',
        gain: { insp: 3, renown: 5 },
        item: 'it_icecore',
        outcome: '它答了，比你复杂一倍。天亮时冰面上多了一小块不化的东西，你捡走了。',
      },
      {
        label: '收摊走人',
        detail: '有些听众不该请',
        gain: { coin: 0.5 },
        outcome: '你走了很远才敢回头。冰上什么也没有，只有你自己的脚印，和另一行。',
      },
    ],
  },
  {
    id: 'ev_choice_lantern',
    title: '挂得最高的那个灯笼',
    text: '祭夜林最高的一枝上挂着一个灯笼，上面的心愿没写字。有人说那是给唱歌的人留的。',
    weight: 7,
    moods: ['forest', 'festive'],
    tone: 'grand',
    choices: [
      {
        label: '爬上去写',
        detail: '你想了一路，最后写了四个字',
        cost: { insp: 2 },
        gain: { renown: 10 },
        item: 'it_lanternslip',
        flag: 'flag_wish_written',
        outcome: '你写的是"别停下来"。写完你才发现，笔迹和灯笼上原来的划痕重叠了。',
      },
      {
        label: '留着，给下一个人',
        detail: '空着也是一种回答',
        gain: { insp: 2.5, coin: 1 },
        outcome: '第二年你回来，那个灯笼还空着。你有点高兴。',
      },
    ],
  },
  {
    id: 'ev_choice_gamble',
    title: '骰子摊的邀请',
    text: '巷口的骰子摊老板认出了你："弹琴的，来一把？赢了，我把这条街的赌局都让你唱开场。"',
    weight: 7,
    moods: ['city', 'desert'],
    tone: 'lucky',
    choices: [
      {
        label: '来一把',
        detail: '赢了三倍，输了赔进去',
        gain: { coin: 2.6 },
        cost: { coin: 1.4 },
        outcome: '你赢了两把，输了一把，净赚。老板笑着说下次不跟你玩了。',
      },
      {
        label: '不赌，只唱开场',
        detail: '稳定的一笔',
        gain: { coin: 1.5, renown: 3 },
        outcome: '你成了这条街每一场赌局的开场。赌客输光的时候也会给你留一枚。',
      },
    ],
  },
  {
    id: 'ev_choice_cat',
    title: '猫不见了',
    text: '瞎眼猫三天没来。码头的老人说，前天在旧仓库那边听见过猫叫。',
    weight: 6,
    moods: ['sea'],
    tone: 'sad',
    once: true,
    choices: [
      {
        label: '去找',
        detail: '摆摊耽误一天',
        cost: { coin: 1.5 },
        item: 'it_catcollar',
        gain: { insp: 2, renown: 4 },
        flag: 'flag_cat_found',
        outcome: '你在仓库夹层里找到了它，还有它的项圈。你只带回了一样。那天你写了《瞎眼猫的进行曲》。',
        song: 'song_cat',
      },
      {
        label: '继续摆摊',
        detail: '它自己会回来的',
        gain: { coin: 1 },
        outcome: '它没有回来。你后来每次弹到第三首都会停半拍，自己也不知道为什么。',
      },
    ],
  },
];

export const EVENT_MAP: Record<string, GameEvent> = Object.fromEntries(
  EVENTS.map((e) => [e.id, e]),
);
