import type { Song } from '../../game/types';

/* ============================================================
   SONGS / SHEET MUSIC — repertoire slots, tags give resonance

   Content module: songs. Values (multipliers, price) and text (name,
   description) still share one file here — songs are small enough that
   the split would cost more than it buys. If a song ever needs art or
   audio of its own, it gets `art.ts` / `audio.ts` siblings and this file
   becomes `values.ts` + `text.ts`. See docs/ARCHITECTURE.md.
   ============================================================ */

export const SONGS: Song[] = [
  {
    id: 'song_ferry',
    name: '《渡船小调》',
    nameEn: 'The Ferryman’s Ditty',
    desc: '所有人都会的那一首。没人会为它多给钱，但没人会走开。',
    tags: ['sea', 'city'],
    mul: { coin: 1.1 },
    price: 0,
    rarity: 'common',
  },
  {
    id: 'song_tide',
    name: '《潮汐摇篮曲》',
    nameEn: 'Tidal Lullaby',
    desc: '写给睡不着的水手。三段，一段比一段慢。',
    tags: ['sea', 'melancholy'],
    mul: { coin: 1.22, insp: 1.1 },
    price: 600,
    rarity: 'common',
  },
  {
    id: 'song_wheat',
    name: '《麦浪圆舞》',
    nameEn: 'Wheatwave Waltz',
    desc: '三拍子，脚会先于人反应。',
    tags: ['wind', 'festive'],
    mul: { coin: 1.3, renown: 1.1 },
    price: 1400,
    rarity: 'common',
  },
  {
    id: 'song_letter',
    name: '《没送到的信》',
    nameEn: 'The Letter Undelivered',
    desc: '你在桥上写的。第一次有人当场哭出来，你还不太会应付。',
    tags: ['melancholy', 'floral', 'city'],
    mul: { coin: 1.28, insp: 1.35, renown: 1.15 },
    price: 3200,
    rarity: 'fine',
  },
  {
    id: 'song_beacon',
    name: '《守夜十二时》',
    nameEn: 'Twelve Hours of Watch',
    desc: '模仿灯塔转灯的节奏，慢得让人安心。',
    tags: ['night', 'sea', 'melancholy'],
    mul: { coin: 1.34, insp: 1.2, leisure: 1.1 },
    price: 7600,
    rarity: 'fine',
  },
  {
    id: 'song_ember',
    name: '《炉火不熄》',
    nameEn: 'Ember Never Cold',
    desc: '有词，但窑工们唱得比你响，所以你渐渐只弹不唱。',
    tags: ['city', 'festive'],
    mul: { coin: 1.55, renown: 1.25, event: 1.1 },
    price: 16000,
    rarity: 'fine',
  },
  {
    id: 'song_rain',
    name: '《伞下二人行》',
    nameEn: 'Two Under One Umbrella',
    desc: '雨天专用。晴天弹它，听起来像在撒谎。',
    tags: ['rain', 'melancholy', 'city'],
    mul: { coin: 1.4, insp: 1.5, leisure: 1.25 },
    price: 12000,
    rarity: 'rare',
  },
  {
    id: 'song_dune',
    name: '《沙记得声音》',
    nameEn: 'The Sand Remembers',
    desc: '没有旋律，只有节奏和停顿。商队的人说这是他们的祖辈的东西。',
    tags: ['desert', 'night', 'sky'],
    mul: { coin: 1.6, insp: 1.55, renown: 1.3 },
    price: 38000,
    rarity: 'rare',
  },
  {
    id: 'song_cloud',
    name: '《云下无人》',
    nameEn: 'No One Below the Cloud',
    desc: '老僧唯一破例听完的一首。他听完什么也没说，只把茶续满了。',
    tags: ['cloud', 'sky', 'holy'],
    mul: { coin: 1.7, insp: 1.85, renown: 1.4 },
    price: 92000,
    rarity: 'rare',
  },
  {
    id: 'song_ice',
    name: '《冰上五线谱》',
    nameEn: 'Staves on Ice',
    desc: '按冰裂的纹路记下来的。弹到第四小节，湖会回应你。',
    tags: ['ice', 'night', 'holy'],
    mul: { coin: 1.85, insp: 2.1, renown: 1.5, event: 1.2 },
    price: 210000,
    rarity: 'myth',
  },
  {
    id: 'song_orchestra',
    name: '《无人的乐团》',
    nameEn: 'Orchestra of No One',
    desc: '你把废墟里散落的十七个声部合成了一部。你一个人演，听起来仍像十七个人。',
    tags: ['ruin', 'melancholy', 'holy'],
    mul: { coin: 1.75, insp: 2.3, renown: 1.6 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_whale',
    name: '《鲸落》',
    nameEn: 'Whalefall',
    desc: '不是你写的。是它教你的。',
    tags: ['sky', 'sea', 'holy', 'night'],
    mul: { coin: 2.4, insp: 2.6, renown: 2.2, event: 1.3 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_wish',
    name: '《挂得最高的那个》',
    nameEn: 'The Highest Lantern',
    desc: '祭夜林里那个没人念出来的心愿，你替它谱了曲。',
    tags: ['forest', 'festive', 'night'],
    mul: { coin: 2.0, insp: 1.7, renown: 1.7, leisure: 1.3 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_cat',
    name: '《瞎眼猫的进行曲》',
    nameEn: 'March of the Blind Cat',
    desc: '荒唐、轻快、莫名其妙地受欢迎。你的第一首原创。',
    tags: ['city', 'festive', 'sea'],
    mul: { coin: 1.35, insp: 1.15, event: 1.15 },
    price: 0,
    rarity: 'fine',
  },
  /* ---- the nine: what a whole ancestral volume sounds like ----
     Not bought, not taught. Each one appears the moment its nine leaves
     are back together (game/systems/scores.ts), which is why every price
     here is zero and every rarity is myth. See content/scores/. */
  {
    id: 'song_vol_tide',
    name: '《九潮》',
    nameEn: 'Nine Tides',
    desc: '一卷·潮的原样。弹到第三段，港里所有的缆绳会同时绷紧一下。',
    tags: ['sea', 'city'],
    mul: { coin: 1.6, insp: 1.45, renown: 1.3 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_wheat',
    name: '《九麦》',
    nameEn: 'Nine Harvests',
    desc: '二卷·麦的原样。婚丧嫁娶都能用同一首曲子，只是速度不同。',
    tags: ['wind', 'festive'],
    mul: { coin: 1.72, insp: 1.4, renown: 1.35, leisure: 1.1 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_petal',
    name: '《九樱》',
    nameEn: 'Nine Petals',
    desc: '三卷·樱的原样。写给要走的人。你第一次弹完，自己先走不动了。',
    tags: ['floral', 'city', 'melancholy'],
    mul: { coin: 1.8, insp: 1.75, renown: 1.4 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_lamp',
    name: '《九灯》',
    nameEn: 'Nine Watches',
    desc: '四卷·灯的原样。整夜的曲子，没有结尾，只有停下来的地方。',
    tags: ['night', 'sea', 'melancholy'],
    mul: { coin: 1.9, insp: 1.8, renown: 1.45, event: 1.1 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_ember',
    name: '《九火》',
    nameEn: 'Nine Kilns',
    desc: '五卷·火的原样。据说照着它烧，器物不裂。你试过一次，确实没裂。',
    tags: ['city', 'festive'],
    mul: { coin: 2.05, insp: 1.85, renown: 1.5 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_sand',
    name: '《九沙》',
    nameEn: 'Nine Sands',
    desc: '六卷·沙的原样。全是节奏和停顿。停顿的地方，风会替你补上。',
    tags: ['desert', 'sky', 'night'],
    mul: { coin: 2.2, insp: 2.0, renown: 1.6, event: 1.15 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_cloud',
    name: '《九云》',
    nameEn: 'Nine Clouds',
    desc: '七卷·云的原样。寺里抄了三百年的那个抄本，错了十一处。',
    tags: ['cloud', 'sky', 'holy'],
    mul: { coin: 2.35, insp: 2.2, renown: 1.7 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_ice',
    name: '《九冰》',
    nameEn: 'Nine Winters',
    desc: '八卷·冰的原样。只在冬至弹。弹完要把谱子冻起来——让它睡。',
    tags: ['ice', 'night', 'holy'],
    mul: { coin: 2.5, insp: 2.4, renown: 1.85, event: 1.2 },
    price: 0,
    rarity: 'myth',
  },
  {
    id: 'song_vol_bone',
    name: '《九骨》',
    nameEn: 'Nine Bones',
    desc: '九卷·骨的原样。不是写下来的，是听下来的。你弹的时候，云会低下来。',
    tags: ['sky', 'sea', 'holy', 'night'],
    mul: { coin: 2.8, insp: 2.7, renown: 2.2, event: 1.3 },
    price: 0,
    rarity: 'myth',
  },
];

export const SONG_MAP: Record<string, Song> = Object.fromEntries(SONGS.map((s) => [s.id, s]));
